linuxdeepin/dtkdevice

debian/control
debian/rules

fix bug VERSION "1.0.0+u006" format invalid
Log:  fix bug VERSIONformat invalid

fix: CMake at CMakeLists_txt12

---

dtklsdevice/3rdparty/cdrom.cpp
dtklsdevice/3rdparty/hw.cpp
dtklsdevice/3rdparty/hw.h
dtklsdevice/3rdparty/nvme.cpp
dtklsdevice/3rdparty/scan.cpp
dtklsdevice/3rdparty/top_process.cpp
dtklsdevice/3rdparty/usb.cpp
dtklsdevice/example/demo_lsdevice.cpp
dtklsdevice/include/dlsdevice.h
dtklsdevice/include/dlsdevicetypes.h
dtklsdevice/src/dlsdevice.cpp
dtklsdevice/src/dlsdevice_p.cpp
dtklsdevice/src/dlsdevice_p.h

add interface deviceCPU-deviceComputer
Log:  add interface deviceCPU-deviceComputer

feat: add interface function for  lsdevice

---

dtklsdevice/docs/dlsdevice.zh_CN.dox
dtklsdevice/docs/dlsdevicetypes.zh_CN.dox

add doc for  lsdevice
Log:  add doc for  lsdevice

feat: add doc for  lsdevice

---

dtkinputdevices/include/dinputdevicetypes.h
dtkinputdevices/src/dbus/inputdevicesinterface.cpp
dtkinputdevices/src/dbus/inputdevicesinterface.h
dtkinputdevices/src/dbus/mouseinterface.cpp
dtkinputdevices/src/dbus/mouseinterface.h
dtkinputdevices/src/dbus/touchpadinterface.cpp
dtkinputdevices/src/dbus/touchpadinterface.h
dtkinputdevices/src/dinputdevice.cpp
dtkinputdevices/src/dinputdevice_p.h
dtkinputdevices/tests/CMakeLists.txt
dtkinputdevices/tests/ut_dinputdevice.cpp

Add DBus proxy for Mouse and TouchPad.
Log: Add DBus proxy

feat: Add DBus proxy

---

dtkinputdevices/include/dinputdevicekeyboard.h
dtkinputdevices/include/dinputdevicemanager.h
dtkinputdevices/include/dinputdevicemouse.h
dtkinputdevices/include/dinputdevicepointer.h
dtkinputdevices/include/dinputdevicesetting.h
dtkinputdevices/include/dinputdevicetablet.h
dtkinputdevices/include/dinputdevicetrackpoint.h
dtkinputdevices/src/CMakeLists.txt
dtkinputdevices/src/dinputdevice.cpp
dtkinputdevices/src/dinputdevicekeyboard.cpp
dtkinputdevices/src/dinputdevicekeyboard_p.h
dtkinputdevices/src/dinputdevicemanager.cpp
dtkinputdevices/src/dinputdevicemanager_p.h
dtkinputdevices/src/dinputdevicesetting.cpp
dtkinputdevices/src/dinputdevicesetting_p.h
dtkinputdevices/src/dinputdevicetablet.cpp
dtkinputdevices/src/dinputdevicetablet_p.h
dtkinputdevices/src/dinputdevicetrackpoint.cpp
dtkinputdevices/src/dinputdevicetrackpoint_p.h
dtkinputdevices/tests/CMakeLists.txt

Finish all device definition(headers).
Log: Finish all headers

feat: Finish adding all devices

---

dtkinputdevices/include/dinputdevice.h
dtkinputdevices/include/dinputdevicekeyboard.h
dtkinputdevices/include/dinputdevicemanager.h
dtkinputdevices/include/dinputdevicemouse.h
dtkinputdevices/include/dinputdevicepointer.h
dtkinputdevices/include/dinputdevicetablet.h
dtkinputdevices/include/dinputdevicetouchpad.h
dtkinputdevices/include/dinputdevicetrackpoint.h
dtkinputdevices/src/dinputdevice.cpp
dtkinputdevices/src/dinputdevicekeyboard.cpp
dtkinputdevices/src/dinputdevicekeyboard_p.h
dtkinputdevices/src/dinputdevicemanager.cpp
dtkinputdevices/src/dinputdevicemanager_p.h
dtkinputdevices/src/dinputdevicemouse.cpp
dtkinputdevices/src/dinputdevicepointer.cpp
dtkinputdevices/src/dinputdevicesetting.cpp
dtkinputdevices/src/dinputdevicetablet.cpp
dtkinputdevices/src/dinputdevicetablet_p.h
dtkinputdevices/src/dinputdevicetouchpad.cpp
dtkinputdevices/src/dinputdevicetrackpoint.cpp
dtkinputdevices/src/dinputdevicetrackpoint_p.h

Add constructors for all devices, complete createDevice.
Log: Complete createDevice interface

feat: Complete createDevice interface

---

dtkinputdevices/examples/CMakeLists.txt
dtkinputdevices/examples/devicemonitor.cpp
dtkinputdevices/include/dinputdevicemanager.h
dtkinputdevices/include/dtkinputdevices_types.h
dtkinputdevices/src/dinputdevicemanager.cpp
dtkinputdevices/src/dinputdevicemanager_p.h
dtkinputdevices/src/dtkinputdevices_converters.cpp
dtkinputdevices/src/dtkinputdevices_converters.h
dtkinputdevices/src/dtkinputdevices_types.cpp

Complete device plug and unplug monitor.
Log: Complete device plug and unplug monitor

feat: Complete plug/unplug signals

---

dtkinputdevices/docs/dinputdevicekeyboard.zh_CN.dox

Add doc for dinputdevicekeyboard.h.
Log: Add doc

docs: Add doc for keyboard

---

dtkinputdevices/include/dinputdevicesetting.h
dtkinputdevices/src/dinputdevicesetting.cpp
dtkinputdevices/src/dinputdevicesetting_p.h

Complete DInputDeviceSetting
Log: Complete DInputDeviceSetting

feat(dtkinputdevices): Complete DInputDeviceSetting

---

dtkinputdevices/tests/fakedbus/inputdevicesservice.cpp
dtkinputdevices/tests/fakedbus/inputdevicesservice.h
dtkinputdevices/tests/fakedbus/keyboardservice.cpp
dtkinputdevices/tests/fakedbus/keyboardservice.h
dtkinputdevices/tests/fakedbus/mouseservice.cpp
dtkinputdevices/tests/fakedbus/mouseservice.h
dtkinputdevices/tests/fakedbus/touchpadservice.cpp
dtkinputdevices/tests/fakedbus/touchpadservice.h
dtkinputdevices/tests/fakedbus/trackpointservice.cpp
dtkinputdevices/tests/fakedbus/trackpointservice.h
dtkinputdevices/tests/fakedbus/wacomservice.cpp
dtkinputdevices/tests/fakedbus/wacomservice.h

Add fakedbus service for dtkinputdevices used for unit tests.
Log: Add fakedbus

tests(dtkinputdevices): Add fakedbus service

---

dtkinputdevices/docs/dinputdevicemouse.zh_CN.dox
dtkinputdevices/docs/dinputdevicepointer.zh_CN.dox
dtkinputdevices/docs/dtkinputdevices_types.zh_CN.dox

Add doc for dinputdevices_types.h、dinputdevicepointer.h、dinputdevicemouse.h
Log: Add doc

docs: Add doc for devicetype、pointer、mouse

---

dtkinputdevices/include/dinputdevice.h
dtkinputdevices/include/dinputdevicesetting.h
dtkinputdevices/include/dinputdevicetouchpad.h
dtkinputdevices/src/dbus/touchpadinterface.h
dtkinputdevices/src/dinputdevicemouse.cpp
dtkinputdevices/src/dinputdevicetouchpad.cpp
dtkinputdevices/tests/CMakeLists.txt
dtkinputdevices/tests/fakedbus/inputdevicesservice.h
dtkinputdevices/tests/fakedbus/keyboardservice.h
dtkinputdevices/tests/fakedbus/mouseservice.h
dtkinputdevices/tests/fakedbus/touchpadservice.h
dtkinputdevices/tests/fakedbus/trackpointservice.h
dtkinputdevices/tests/fakedbus/wacomservice.h
dtkinputdevices/tests/ut_dinputdevice.cpp
dtkinputdevices/tests/ut_dinputdevicemouse.cpp
dtkinputdevices/tests/ut_dinputdevicepointer.cpp
dtkinputdevices/tests/ut_dinputdevicetouchpad.cpp

Add unit tests for DInputDevice, DInputDevicePointer, DInputDeviceMouse, DInputDeviceTouchPad. Fix some bugs found by unit tests. Correct some usage of signals and slots.
Log: Add unit tests

tests(dtkinputdevices): Add unit tests

---

dtkinputdevices/src/dinputdevicesetting.cpp

Add Q_UNUSED to fix compile warnings.
Log: Fix compile warnings

chore: Fix compile warnings

---

dtkinputdevices/docs/index.en_US.md
dtkinputdevices/docs/index.zh_CN.md
dtkinputdevices/examples/devicemonitor.cpp
dtkinputdevices/include/dtkinputdevices_types.h
dtkinputdevices/src/dtkinputdevices_converters.cpp
dtkinputdevices/src/dtkinputdevices_converters.h
dtkinputdevices/src/dtkinputdevices_types.cpp

Add a complete example (device monitor) and document for it.
Log: add device monitor

chore: complete examples

---

dtklsdevice/example/demo_lsdevice.cpp
dtklsdevice/include/dcpudevice.h
dtklsdevice/include/dlsdevice.h
dtklsdevice/include/dlsdevicetypes.h
dtklsdevice/include/dmemorydevice.h
dtklsdevice/src/CMakeLists.txt
dtklsdevice/src/dcpudevice.cpp
dtklsdevice/src/dlsdevice.cpp
dtklsdevice/src/dlsdevice_p.cpp
dtklsdevice/src/dlsdevice_p.h
dtklsdevice/src/dmemorydevice.cpp

Add cpu and memory interface
Log: cpu and memory interface

feat: Add cpu and memory interface

---

dtklsdevice/include/dcpudevice.h
dtklsdevice/include/ddiskdevice.h
dtklsdevice/include/dinputdevice.h
dtklsdevice/include/dlsdevice.h
dtklsdevice/include/dlsdevicetypes.h
dtklsdevice/include/dmemorydevice.h
dtklsdevice/include/dmotherboarddevice.h
dtklsdevice/include/dnetdevice.h
dtklsdevice/include/dprocessdevice.h
dtklsdevice/src/dcpudevice.cpp
dtklsdevice/src/ddiskdevice.cpp
dtklsdevice/src/dinputdevice.cpp
dtklsdevice/src/dmemorydevice.cpp
dtklsdevice/src/dmotherboarddevice.cpp
dtklsdevice/src/dnetdevice.cpp
dtklsdevice/src/dprocessdevice.cpp

Add disk input motherboard network and dprocess interface
Log: disk input motherboard network and dprocess interface

feat: Add disk input motherboard network and dprocess interface

---

.reuse/dep5
dtklsdevice/docs/CMakeLists.txt
dtklsdevice/docs/dcpudevice.zh_CN.dox
dtklsdevice/docs/ddiskdevice.zh_CN.dox
dtklsdevice/docs/dinputdevice.zh_CN.dox
dtklsdevice/docs/dlsdevice.zh_CN.dox
dtklsdevice/docs/dlsdevicetypes.zh_CN.dox
dtklsdevice/docs/dmemorydevice.zh_CN.dox
dtklsdevice/docs/dmotherboarddevice.zh_CN.dox
dtklsdevice/docs/dnetdevice.zh_CN.dox
dtklsdevice/docs/dprocessdevice.zh_CN.dox
dtklsdevice/include/dlsdevicetypes.h
dtklsdevice/include/dmemorydevice.h
dtklsdevice/include/dmotherboarddevice.h
dtklsdevice/include/dtklsdevice_global.h
dtklsdevice/src/dmemorydevice.cpp
dtklsdevice/src/dmotherboarddevice.cpp

add dox for dtkdevice(dtklsdevice)
Log: add dox for dtkdevice(dtklsdevice)

feat: add dox for dtkdevice(dtklsdevice)

---

dtklsdevice/src/dcpudevice.cpp
dtklsdevice/src/ddiskdevice.cpp
dtklsdevice/src/dinputdevice.cpp
dtklsdevice/src/dmemorydevice.cpp
dtklsdevice/src/dmotherboarddevice.cpp
dtklsdevice/src/dnetdevice.cpp
dtklsdevice/src/dprocessdevice.cpp

Add disk  interface data(dtklsdevice)
Log: Add disk  interface data(dtklsdevice)

feat: Add disk  interface data

---

CMakeLists.txt
debian/rules

Modify the version parameter
Log: modify the version parameter

feat: change the version parameter

---

include/lsdevice/dlsdevice.h
src/3rdparty/disk.cpp
src/3rdparty/packet.h
src/lsdevice/dnetdevice.cpp
src/lsdevice/dprocessdevice.cpp

Add data for dprocessdevice and dnetdevice
Log: Add data for dprocessdevice and dnetdevice

feat: Add data for dprocessdevice and dnetdevice

---

.reuse/dep5
LICENSES/MIT.txt
src/lsdevice/dmemorydevice.cpp
tests/3rdparty/cpp-stub/LICENSE
tests/3rdparty/cpp-stub/addr_any.h
tests/3rdparty/cpp-stub/addr_pri.h
tests/3rdparty/cpp-stub/elfio.hpp
tests/3rdparty/cpp-stub/stub.h
tests/3rdparty/stub-ext/stub-shadow.cpp
tests/3rdparty/stub-ext/stub-shadow.h
tests/3rdparty/stub-ext/stubext.h
tests/CMakeLists.txt
tests/lsdevice/ut_dcpudevice.cpp
tests/lsdevice/ut_ddiskdevice.cpp
tests/lsdevice/ut_dinputdevice.cpp
tests/lsdevice/ut_dmemorydevice.cpp
tests/lsdevice/ut_dmotherboarddevice.cpp
tests/lsdevice/ut_dnetdevice.cpp
tests/lsdevice/ut_dprocessdevice.cpp
tests/lsdevice/ut_lsdevice.cpp

Add ut_test for lsdevice
Log: Add ut_test for lsdevice

feat: Add ut_test for lsdevice

---

debian/changelog

Update changelog for dtkdevice
Log: Update changelog for dtkdevice

feat: Update changelog for dtkdevice

---

CMakeLists.txt
debian/changelog

Release 1.0.3
Log: update changelog to 1.0.3

feat: update changelog

---

src/lsdevice/dmemorydevice.cpp
src/lsdevice/dnetdevice.cpp

1. 不同 Qt 版本使用不一样的 behavior
2. 要用不带 .h 的头文件否则容易引用错误的头文件
Log: build

fix: build error

---

.gitignore

对.gitignore进行修改，防止doxygen-theme对项目污染
Log: 增加了文件忽视规则,防止doxygen-theme对项目污染
Issue: https://github.com/linuxdeepin/dtk/issues/99

chore: add rules to .gitignore
